spring:
  web:
    resources:
      add-mappings: true
      cache:
        cache control:
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true
      static-locations: classpath:/static/



  thymeleaf:
    cache: false

  redis:
    host: 192.168.215.128
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
#        最大空闲连接
        max-idle: 200
#        最小空闲连接
        min-idle: 5
  rabbitmq:
    host: 192.168.215.128
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        max-concurrency: 10
        #限制消费者每次只处理一条消息,处理完再继续吓一条消息
        prefetch: 1
        #启动时是否默认启动容器,默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试,默认false
        enabled: true
        #重试时间,默认1000ms
        initial-interval: 1000ms
        #重试最大次数,默认3次
        max-attempts: 3
        #重试最大间隔时间,默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数,比如配2.0,第一次就等10秒,第二次就等20秒,第三次40秒
        multiplier: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: "root"
    password: 1234
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 8000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.yeyeee.seckill.entity

logging:
  level:
    com.yeyeee.seckill.mapper: debug
